version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_DB_PORT}:27017"
    networks:
      - dev

volumes:
  mongo_data:
    driver: local

networks:
    dev:
      external: true
      name: dev
