version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the latest stable version or specify your desired version
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data
    ports:
      - "${POSTGRES_PORT}:5432"  # Map the container's port 5432 to the host machine
    networks:
      - dev

volumes:
  postgres_data:
    driver: local

networks:
  dev:
    external: true
    name: dev