
server:
  address: 0.0.0.0
  port: 8090

log:
  file_name: "app.log"
  max_size: 1000    # Max size in MB before rotation
  max_backups: 5    # Max number of backup files to retain
  max_age: 30       # Max age in days for log retention
  compress: true    # Whether to compress rotated files
  log_mode: "text"  # Log format: json or text