version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the latest stable version or specify your desired version
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data
    ports:
      - "5432:5432"  # Map the container's port 5432 to the host machine

volumes:
  postgres_data:
    driver: local